name: Backup and Test Script with Docker MySQL


on:
  push:
    branches:
      - '**'     # Matches every branch 

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2    
    - name: Set up Docker Buildx    
      uses: docker/setup-buildx-action@v1
   

    - name: Build Docker image
      run: docker build -t sehvenider/mysql-backup-test:1.0.1 .   # Builds a Docker image with the specified tag and version.
    - name: Run MySQL container
      run: docker run --name mycontainer -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -d sehvenider/mysql-backup-test:1.0.1 --max-allowed-packet=1073741824
            
    - name: Wait for MySQL to start
      run: sleep 5s

    - name: Run script in Docker container
      run: docker exec mycontainer backup.sh  # Executes the 'backup.sh' script within the running MySQL container.

    - name: Clean up Docker resources
      run: docker stop mycontainer && docker rm mycontainer
