name: Backup and Test Script with Docker MySQL

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t sehvenider/s:1.0.5 .

    - name: Run MySQL container
      run: docker run --name mysql-container -e MYSQL_ROOT_PASSWORD=password -d sehvenider/s:1.0.5

    - name: Wait for MySQL to start
      run: sleep 30s

    - name: Run script in Docker container
      run: docker exec -it backup-zip.sh

    - name: Clean up Docker resources
      run: docker stop mysql-container && docker rm mysql-container
  
