name: Backup and Test Script with Docker MySQL

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build Docker image
      run: docker build -t sehvenider/s:1.0.5 .

    - name: Run MySQL container
      run: docker run --name mycontainer -e MYSQL_ROOT_PASSWORD="secret" -d sehvenider/s:1.0.5

    - name: Wait for MySQL to start
      run: sleep 5s

    - name: Run script in Docker container
      run: docker exec mycontainer backup-zip.sh root secret

    - name: Clean up Docker resources
      run: docker stop mycontainer && docker rm mycontainer
  
